### ISSUE TITLE
Do not register ElasticSearch Connection by default in ext_localconf.php

### ISSUE THREAD

**Issue by martinhummer** [Codappix/search_core#111]
search_core registers the ElasticSearch Connection by default in ext_localconf.php:
https://github.com/Codappix/search_core/blob/develop/ext_localconf.php#L40

It should be possible not to use ElasticSearch at all.

**Comment by DanielSiepmann** [comment]
We will split search_core and search_elasticsearch in the future. Due to the lack of time (no one will pay that) it will not happen very soon.

We therefore have to make the current state compatible.

Possible solutions are:

- We remove the code and mention it in docs, so an integrator has to add it, e.g. his sitepackage.
- We add extension configuration (extension manager) and will check that whether elasticsearch is active.
